name: "CI"
on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup build tools
        run: |
          sudo apt purge --auto-remove cmake
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
          sudo apt update
          sudo apt install kitware-archive-keyring
          sudo rm /etc/apt/trusted.gpg.d/kitware.gpg
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          pkg-config \
          cmake \
          build-essential \
          ninja-build \
          libjpeg-dev \
          libnss3-dev \
          ca-certificates \
          libcurl4-nss-dev \
          liblcms2-dev \
          libboost-container-dev \
          libopenjp2-7-dev \
          libfreetype-dev \
          libfontconfig1-dev

      - name: Build and install poppler cpp
        run: |
          cd poppler-wrapper-lib
          cp ./3rd-party/* /tmp
          cd /tmp
          tar -xvf poppler-data-0.4.11.tar.gz
          cd poppler-data-0.4.11 && sudo make install
          cd ..
          tar -xvf poppler-21.09.0.tar.xz
          cd poppler-21.09.0
          mkdir -p build && cd build && cmake -G Ninja \
          -DBUILD_GTK_TESTS=OFF \
          -DENABLE_QT5=OFF \
          -DENABLE_QT6=OFF \
          -DENABLE_GLIB=OFF \
          -DBUILD_QT5_TESTS=OFF \
          -DBUILD_QT6_TESTS=OFF \
          -DBUILD_MANUAL_TESTS=OFF \
          -DCMAKE_INSTALL_PREFIX:PATH=/usr \
          ..

          ninja
          sudo cmake --install . --prefix /usr

      - name: Build and Test cpp library
        run: |
          pwd
          ls -al
          cd poppler-wrapper-lib
          ./run-cmake.sh
          ./run-tests.sh

      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "5.0.x"
      - name: Install dependencies
        run: cd dotnet && dotnet restore
      - name: Build
        run: cd dotnet && dotnet build --configuration Release --no-restore
      - name: Test
        run: cd dotnet && dotnet test --no-restore --verbosity normal
